---
title: "Mini_Project3"
author: "Nichole, Rowan, Yuqing "
date: "11/13/2017"
output: html_document
---
```{r, message=FALSE}
library(mdsr)
library(RMySQL)
library(dplyr)
db <- dbConnect_scidb(dbname = "imdb")
big_data<- db%>% 
  dbGetQuery("SELECT ml.movie_id, ml.linked_movie_id, ml.link_type_id, t.title AS movie_title, t2.title AS linked_movie_title, t.production_year AS original_year, t2.production_year AS sequels_year, t2.production_year - t.production_year AS year_difference
FROM movie_link ml
JOIN title t ON ml.movie_id = t.id
JOIN title t2 ON ml.linked_movie_id = t2.id
JOIN movie_info mi On t.id = mi.movie_id
WHERE ml.link_type_id =2 
AND mi.info_type_id = 8
AND info = 'USA'
AND t.kind_id = 1
AND t2.kind_id = 1;")
#using "mi.info_type_id = 8" then filter "info='USA'"is index, saving time of calculation

```

```{r, message=FALSE}
d1<- big_data %>%
  group_by(sequels_year)%>%
  summarize(total = n())
d2 <- big_data %>%
  group_by(original_year)%>%
  summarize(total = n())
d3 <- d1%>%
  full_join(d2, by = c("sequels_year" = "original_year"))
d1
d2
d3 #x: sequels y:original
d4<- d3%>%
  mutate(decade = 10 * floor(sequels_year / 10)) %>%
  group_by(decade)%>%
  summarize(sequels = sum(total.x),
          original = sum(total.y))
d4
```

<<<<<<< HEAD
```{r, message=FALSE}
library(ggplot)
library(dplyr)
library(scales)
ggplot(d4,aes(x = , y = ,fill = ind)) + 
    geom_bar(position = "fill",stat = "identity") +
    # or:
    # geom_bar(position = position_fill(), stat = "identity") 
    scale_y_continuous(labels = percent_format())
=======
```{r,message=FALSE}
# Bar graph (total)

>>>>>>> e7b4223869ca47c928d1f4f0b0dfd42baba626e6
```

